// Deterministic markdown generators used by MockProvider. Same input +
// same skill => byte-identical output (no timestamps in the body).
import type { Skill } from './skills.ts';

function sentences(text: string): string[] {
  return text
    .split(/\r?\n+/)
    .map((l) => l.replace(/^[-*•\s]+/, '').trim())
    .filter((l) => l.length > 0 && !l.startsWith('#'));
}

function pick(lines: string[], re: RegExp): string[] {
  return lines.filter((l) => re.test(l));
}

function bullets(lines: string[], fallback = '- _None captured from source notes._'): string {
  if (!lines.length) return fallback;
  return lines.map((l) => `- ${l.charAt(0).toUpperCase()}${l.slice(1)}`).join('\n');
}

function extractTags(text: string): string[] {
  return [...new Set(text.match(/#[a-z0-9][\w-]*/gi) ?? [])];
}

function footer(skill: Skill, providerId: string): string {
  return [
    '---',
    '',
    `> Draft generated by \`${providerId}\` using skill **${skill.name}** ` +
      `(\`${skill.relPath}\`, hash \`${skill.shortHash}\`). Review before sharing.`,
  ].join('\n');
}

const RE_DECISION = /\b(decid\w*|decision\w*|agreed|we will|going with|chose|approved)\b/i;
const RE_RISK = /\b(risk|blocker|blocked|concern|gap|issue|problem|worried|threat)\b/i;
const RE_FOLLOWUP = /\b(todo|to do|follow[- ]?up|tomorrow|next step|need to|ping|remind|draft the)\b/i;
const RE_ARCH = /\b(architect|design|strategy|platform|harness|pattern|canon|standard|principle|boundar)\b/i;
const RE_PEOPLE = /\b(met with|meeting|talked to|spoke with|call with|with the|team|director|stakeholder|1:1)\b/i;

export function genDailyLog(args: {
  date: string;
  notes: string;
  skill: Skill;
  providerId: string;
  sourceRef: string;
}): string {
  const { date, notes, skill, providerId, sourceRef } = args;
  const lines = sentences(notes);
  const decisions = pick(lines, RE_DECISION);
  const risks = pick(lines, RE_RISK);
  const followups = pick(lines, RE_FOLLOWUP);
  const arch = pick(lines, RE_ARCH);
  const people = pick(lines, RE_PEOPLE);
  const classified = new Set([...decisions, ...risks, ...followups]);
  const work = lines.filter((l) => !classified.has(l));
  const tags = extractTags(notes);
  const summary =
    lines.length > 0
      ? `${lines.length} note item${lines.length === 1 ? '' : 's'} captured. Key thread: ${lines[0]}`
      : 'No substantive notes captured for this day.';

  return [
    `# Daily Work Log — ${date}`,
    '',
    '## Executive Summary',
    summary,
    '',
    '## Work Completed',
    bullets(work),
    '',
    '## Architecture / Strategy Notes',
    bullets(arch),
    '',
    '## Decisions',
    bullets(decisions),
    '',
    '## Risks / Blockers',
    bullets(risks),
    '',
    '## Follow-ups',
    bullets(followups),
    '',
    '## People / Stakeholders',
    bullets(people, '- _No stakeholders mentioned._'),
    '',
    '## Tags',
    tags.length ? tags.join(' ') : '#daily-log',
    '',
    '## Source Notes Used',
    `- ${sourceRef}`,
    '',
    footer(skill, providerId),
    '',
  ].join('\n');
}

/** Pull the bullet lines of a `## Section` out of a markdown doc. */
export function extractSection(md: string, heading: string): string[] {
  const lines = md.split(/\r?\n/);
  const out: string[] = [];
  let inSection = false;
  for (const line of lines) {
    if (/^##\s+/.test(line)) {
      inSection = line.replace(/^##\s+/, '').trim().toLowerCase() === heading.toLowerCase();
      continue;
    }
    if (inSection && /^\s*-\s+/.test(line)) {
      const item = line.replace(/^\s*-\s+/, '').trim();
      if (item && !item.startsWith('_None') && !item.startsWith('_No ')) out.push(item);
    }
  }
  return out;
}

export function genWeeklyReport(args: {
  weekLabel: string;
  logs: Array<{ name: string; content: string }>;
  skill: Skill;
  providerId: string;
}): string {
  const { weekLabel, logs, skill, providerId } = args;
  const all = (h: string) => [...new Set(logs.flatMap((l) => extractSection(l.content, h)))];
  const work = all('Work Completed');
  const arch = all('Architecture / Strategy Notes');
  const decisions = all('Decisions');
  const risks = all('Risks / Blockers');
  const followups = all('Follow-ups');

  return [
    `# Weekly Report — ${weekLabel}`,
    '',
    '## Executive Summary',
    `This week covered ${logs.length} logged day${logs.length === 1 ? '' : 's'} with ` +
      `${work.length} delivery items, ${decisions.length} decision${decisions.length === 1 ? '' : 's'}, and ` +
      `${risks.length} active risk${risks.length === 1 ? '' : 's'}. ` +
      (arch[0] ? `Strategic focus: ${arch[0]}` : 'Strategic focus: platform architecture continuity.'),
    '',
    '## Strategic Progress',
    bullets(arch, '- _No explicit architecture/strategy items in this week’s logs._'),
    '',
    '## Delivery Evidence',
    bullets(work),
    '',
    '## Decisions / Alignment Needed',
    bullets(decisions, '- _No decisions recorded this week._'),
    '',
    '## Risks / Gaps / Tradeoffs',
    bullets(risks, '- _No risks recorded this week._'),
    '',
    '## Next Week Focus',
    bullets(followups.slice(0, 8), '- _No follow-ups carried into next week._'),
    '',
    '## Source Logs',
    logs.map((l) => `- ${l.name}`).join('\n') || '- _None_',
    '',
    footer(skill, providerId),
    '',
  ].join('\n');
}

/** Human title for an output type, e.g. 'review-packet' -> 'Review Packet'. */
function typeTitle(outputType: string): string {
  return outputType
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\b(Adr|Qa)\b/g, (m) => m.toUpperCase());
}

/**
 * Generic deterministic generator for workflow output types that don't have
 * a dedicated generator above (ADRs, review packets, planning briefs, ...).
 * Same keyword-extraction approach as genDailyLog, shaped into a neutral
 * artifact structure that all generic workflows share.
 */
export function genGeneric(args: {
  outputType: string;
  label: string;
  inputText: string;
  sources: Array<{ name: string; content: string }>;
  skill: Skill;
  providerId: string;
  sourceRef: string;
}): string {
  const { outputType, label, inputText, sources, skill, providerId, sourceRef } = args;
  // inputText already includes selected file contents (the engine composes it
  // that way for the provider prompt), so extract from it alone.
  const lines = sentences(inputText);
  const decisions = pick(lines, RE_DECISION);
  const risks = pick(lines, RE_RISK);
  const followups = pick(lines, RE_FOLLOWUP);
  const classified = new Set([...decisions, ...risks, ...followups]);
  const keyPoints = lines.filter((l) => !classified.has(l)).slice(0, 20);

  return [
    `# ${typeTitle(outputType)} — ${label}`,
    '',
    '## Summary',
    lines.length
      ? `Drafted from ${sources.length ? `${sources.length} source file(s)` : 'pasted notes'}: ` +
        `${keyPoints.length} key points, ${decisions.length} decision item(s), ${risks.length} risk(s), ${followups.length} follow-up(s).`
      : 'No substantive input captured.',
    '',
    '## Key Points',
    bullets(keyPoints),
    '',
    '## Decisions',
    bullets(decisions, '- _No decisions found in the input._'),
    '',
    '## Risks / Open Questions',
    bullets(risks, '- _No risks or open questions found._'),
    '',
    '## Follow-ups / Actions',
    bullets(followups, '- _No follow-ups found._'),
    '',
    '## Source Notes Used',
    sources.length ? sources.map((s) => `- ${s.name}`).join('\n') : `- ${sourceRef}`,
    '',
    footer(skill, providerId),
    '',
  ].join('\n');
}

const RE_SENSITIVE = /\b(met with|talked to|spoke with|1:1|salary|budget|\$\d|vendor|hr\b|ping)\b/i;
const RE_NAME_LIKE = /\b(?:with|from|to)\s+[A-Z][a-z]+\b/;

export function genWikiSource(args: {
  date: string;
  sources: Array<{ name: string; content: string }>;
  skill: Skill;
  providerId: string;
}): string {
  const { date, sources, skill, providerId } = args;
  const all = (h: string) => [...new Set(sources.flatMap((s) => extractSection(s.content, h)))];
  const raw = {
    updates: [...new Set([...all('Work Completed'), ...all('Delivery Evidence'), ...all('Strategic Progress')])],
    decisions: [...new Set([...all('Decisions'), ...all('Decisions / Alignment Needed')])],
    open: [...new Set([...all('Risks / Blockers'), ...all('Risks / Gaps / Tradeoffs'), ...all('Follow-ups')])],
  };
  const excludedCounts = { stakeholder: 0, sensitive: 0 };
  const sanitize = (items: string[]) =>
    items.filter((i) => {
      if (RE_SENSITIVE.test(i)) {
        excludedCounts.sensitive++;
        return false;
      }
      if (RE_NAME_LIKE.test(i)) {
        excludedCounts.stakeholder++;
        return false;
      }
      return true;
    });
  const updates = sanitize(raw.updates);
  const decisions = sanitize(raw.decisions);
  const open = sanitize(raw.open);

  return [
    `# Wiki Source — ${date}`,
    '',
    '## Summary',
    `Sanitized source material distilled from ${sources.length} note file${sources.length === 1 ? '' : 's'}: ` +
      `${updates.length} update items, ${decisions.length} durable decisions, ${open.length} open questions.`,
    '',
    '## Major Updates',
    bullets(updates),
    '',
    '## Decisions',
    bullets(decisions, '- _No durable decisions in reviewed material._'),
    '',
    '## Open Questions',
    bullets(open, '- _No open questions carried forward._'),
    '',
    '## Suggested Wiki Updates',
    bullets(
      decisions.slice(0, 5).map((d) => `Reflect in canon/wiki: ${d}`),
      '- _No wiki updates suggested._',
    ),
    '',
    '## Source Notes Reviewed',
    sources.map((s) => `- ${s.name}`).join('\n') || '- _None_',
    '',
    '## Excluded Material',
    [
      `- ${excludedCounts.stakeholder} item(s) excluded: stakeholder/person references.`,
      `- ${excludedCounts.sensitive} item(s) excluded: meetings, costs, or vendor/HR-adjacent content.`,
    ].join('\n'),
    '',
    footer(skill, providerId),
    '',
  ].join('\n');
}
